tree: /bt_xml/source_patrol.xml
waypoints:
  - name: wp1
    x: -1.7
    y: -0.5
  - name: wp2
    x: 1.42
    y: -1.14
  - name: wp3
    x: 1.58
    y: 1.28
  - name: wp4
    x: -1.18
    y: 1.61
    