source_tree: /bt_xml/source_patrol.xml
nodes: 5
missions:
  - patrol
waypoints:
  - id: wp1
    x: -1.7
    y: -0.5
  - id: wp2
    x: 1.42
    y: -1.14
  - id: wp3
    x: 1.58
    y: 1.28
  - id: wp4
    x: -1.7
    y: -0.5
  - id: wp5
    x: 1.42
    y: -1.14
  - id: wp6
    x: 1.58
    y: 1.28
  - id: wp7
    x: -1.7
    y: -0.5
  - id: wp8
    x: 1.42
    y: -1.14
  - id: wp9
    x: 1.58
    y: 1.28
  - id: wp10
    x: -1.7
    y: -0.5
  - id: wp11
    x: 1.42
    y: -1.14
  - id: wp12
    x: 1.58
    y: 1.28
  - id: wp13
    x: -1.7
    y: -0.5
  - id: wp14
    x: 1.42
    y: -1.14
  - id: wp15
    x: 1.58
    y: 1.28
  - id: wp16
    x: -1.7
    y: -0.5
  - id: wp17
    x: 1.42
    y: -1.14
  - id: wp18
    x: 1.58
    y: 1.28
  - id: wp19
    x: -1.7
    y: -0.5
  - id: wp20
    x: 1.42
    y: -1.14
  - id: wp21
    x: 1.58
    y: 1.28
  - id: wp22
    x: -1.7
    y: -0.5
  - id: wp23
    x: 1.42
    y: -1.14
  - id: wp24
    x: 1.58
    y: 1.28
  - id: recharge
    x: -1.18
    y: 1.61
    