source_tree: /bt_xml/source_2patrol.xml
nodes: 5
missions:
  - patrol
waypoints:
  - id: wp1
    x: 1.6
    y: 4.5
  - id: wp2
    x: -8.0
    y: -3.0
  - id: wp3
    x: 7.0
    y: -2.0
  - id: wp4
    x: -8.0
    y: 0.0
  - id: wp5
    x: 0.0
    y: 0.0
  - id: wp6
    x: 0.0
    y: -4.0
  - id: wp7
    x: -7
    y: -3.5
  - id: recharge
    x: -8.0
    y: -3.0
    