source_tree: /bt_xml/source_2patrol.xml
nodes: 5
missions:
  - patrol
waypoints:
  - id: wp1
    x: 1.5
    y: 4.0
  - id: wp2
    x: 3.7
    y: 1.0
  - id: wp3
    x: 5.0
    y: 0.15
  - id: wp3
    x: 5.0
    y: 0.15
  - id: wp4
    x: 7.0
    y: 1.5
  - id: wp5
    x: 5.0
    y: 0.15
  - id: wp6
    x: 3.0
    y: -3.5
  - id: recharge
    x: -7.5
    y: -3.0
    