source_tree: /bt_xml/source_3patrol.xml
nodes: 5
missions:
  - patrol
waypoints:
  - id: wp1
    x: 2.46
    y: 1.55
  - id: wp2
    x: 3.96
    y: 0.12
  - id: wp3
    x: -2.8
    y: -1.67
  - id: recharge
    x: -5.8
    y: -3.3
    