source_tree: /bt_xml/source_patrol.xml
nodes: 5
missions:
  - patrol
waypoints:
  - id: wp1
    x: -1.7
    y: -0.5
  - id: wp2
    x: 1.42
    y: -1.14
  - id: wp3
    x: 1.58
    y: 1.28
  - id: wp4
    x: -1.18
    y: 1.61
    